routes/DataRoutes.py
from flask import Blueprint, render_template

from helpers import authRequired

bp = Blueprint('DataRoutes', __name__)

@bp.route('/data', methods=['GET'])
@authRequired.login_required
def show_data():
        return render_template('menu/data.html')

routes/ModelRoutes.py
import os
from controllers import ModelController
from helpers import authRequired, detect, savingFile
from werkzeug.utils import secure_filename
from flask import Blueprint, render_template, request, flash, redirect, url_for, send_from_directory, session

bp = Blueprint('ModelRoutes', __name__)

controller = ModelController()

@bp.route('/uploads/<folder>/<path:filename>')
def get_file(folder, filename):
        path_dir = os.path.join('../uploads', folder )

        return send_from_directory(path_dir, filename)

@bp.route('/model', methods=['GET', 'POST'])
@authRequired.login_required
def show_model():
        # menangani method GET
        if request.method == 'GET':
                return render_template('menu/model.html')
        # menangani method POST
        elif request.method == 'POST':
                # NO FILE
                if 'file' not in request.files:
                        flash('Tidak ada file yang dikirim')
                        return render_template('menu/model.html')
                
                file = request.files['file']

                # IF FILE DON'T HAVE NAME
                if file.filename == '':
                        flash('Tidak ada foto yang dipilih')
                        return redirect(request.url)
                
                if file and savingFile.allowed_file(file.filename):
                        # filename = secure_filename(file.filename)

                        # SAVE FILE ON USER FOLDER
                        data_save = savingFile.save_file(file)

                        if(data_save['message'] == 'exist'):
                                flash('Gambar sudah diklasifikasi, cek menu Hasil Klasifikasi')
                                return render_template('menu/model.html')
                        
                        # DETECT IMAGE
                        data_detect= detect.detect_lite(folder=data_save['folder'], filename=data_save['filename'])
                        
                        # return data_detect
                        
                                # return redirect(url_for('BerandaRoutes.show_penjelasan'))
                        # SAVE TO DB
                        user = session.get('username')
                        saving_file = controller.save_file(user, data_save['filename'], data_detect['class name'], data_detect['score'])

                        if(saving_file['message'] == 'success'):
                                flash('File berhasil di klasifikasi !')
                        # mengembalikan laman model.html dengan nama kelas hasil deteksi
                        return render_template('menu/model.html', class_name=data_detect['class name'], folder=data_save['folder'], filename=data_save['filename'], score=round(data_detect['score'],2))
                
                flash('File yang dimasukkan salah')
                return redirect(request.url)

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="http://127.0.0.1:5000/static/flashjs-master/dist/flash.min.js"></script>
    <link rel="stylesheet" href="http://127.0.0.1:5000/static/flashjs-master/dist/flash.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/tw-elements.min.css" />
    <title>{% block title %} {% endblock %}</title>
</head>


<body>
    {% include 'base/topbar.html' %}

    {% include 'base/leftbar.html' %}

    <div class="w-5/6 absolute right-0 mt-16">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul class='absolute  w-full rounded p-3 h-10'>
                {% for message in messages %}
                <li class="text-red-300 text-3xl ">{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
        {% block content %} {% endblock %}
    </div>
    
</body>
</html>

templates/base/leftbar.html
    <div class="w-1/6 h-screen fixed flex justify-center border-r mt-16 py-5">
        <ul class="flex flex-col gap-10 text-2xl">
            <a href="{{ url_for('BerandaRoutes.show_penjelasan')}}" class="bg-blue-300 p-2 text-slate-100 rounded-lg cursor-pointer {% if (url_for(request.endpoint, **request.view_args) == '/')%} bg-blue-500 {%endif%}"><li class="">Beranda</li></a>
            <a href="{{ url_for('DataRoutes.show_data')}}" class="bg-blue-300 p-2 text-slate-100 rounded-lg  cursor-pointer{% if (url_for(request.endpoint, **request.view_args) == '/data')%} bg-blue-500 {%endif%}"><li class="">Data Terbaru</li></a>
            <a href="{{ url_for('ModelRoutes.show_model')}}" class="bg-blue-300 p-2 text-slate-100 rounded-lg  cursor-pointer{% if (url_for(request.endpoint, **request.view_args) == '/model')%} bg-blue-500 {%endif%}"><li>Model Deteksi</li></a>
            <a href="{{ url_for('HasilRoutes.show_data')}}" class="bg-blue-300 p-2 text-slate-100 rounded-lg  cursor-pointer{% if (url_for(request.endpoint, **request.view_args) == '/hasil')%} bg-blue-500 {%endif%}"><li>Hasil Deteksi</li></a>
            {% if session.is_admin %}
            <a href="{{ url_for('KepadatanRoutes.show_kepadatan')}}" class="bg-blue-300 p-2 text-slate-100 rounded-lg  cursor-pointer{% if (url_for(request.endpoint, **request.view_args) == '/kepadatan')%} bg-blue-500 {%endif%}"><li>Menghitung Kepadatan</li></a>
            {% endif %}
        </ul>
    </div>

templates/base/topbar.html
<nav class="bg-gray-50 p-4 fixed w-screen top-0 left-0 mb-16 z-10">
    <div class="container mx-auto flex justify-between items-center">
        <!-- Logo -->
        <div class="text-blue-400 font-bold">
            Logo
        </div>

        <!-- Navbar items -->
        <ul class="flex space-x-4">
            <li class="text-blue-400">
                Welcome, <span class="font-bold">{{ session.username }}</span> <!-- Replace with session information -->
            </li>
            <li>
                <!-- Logout button -->
                <form action="/logout" method="post">
                    <button type="submit" class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded">Logout</button>
                </form>
            </li>
        </ul>
    </div>
</nav>