controllers/HasilController.py
from helpers.connecttion import db

class HasilController(object):
        def __init__(self):
            pass
        def get_file_user(self, user):
            try:
                cursor = db.connection.cursor()
                cursor.execute("""SELECT * FROM tbl_gambar WHERE user=(%s)""", (user,))
                data = cursor.fetchall()
                cursor.close()
                
                return ({'message': 'success', 'data' : data})
            
            except Exception as e:
                return ({'message' : 'error', 'data' : e})
        
        def delete_file_user(self, user, filename):
            try:
                cursor = db.connection.cursor()
                cursor.execute("""DELETE FROM tbl_gambar WHERE user=(%s) AND nama_gambar=(%s)""", (user, filename))
                db.connection.commit()
                cursor.close()

                return ({'message': 'success'})
            
            except Exception as e:
                return ({'message' : 'error', 'data' : e})

controllers/KepadatanController.py
from datetime import datetime
from helpers.connecttion import db

class KepadatanController(object):
        def __init__(self):
            pass

        def create_data_desa(self,nama_desa, jml_orang):
            try:
                now = datetime.now()    
                cursor = db.connection.cursor()
                cursor.execute("""INSERT INTO tbl_kepadatan_keong VALUES(DEFAULT, %s, DEFAULT, %s, DEFAULT, DEFAULT, %s)""", (nama_desa, jml_orang, now.date()))
                db.connection.commit()
                cursor.close()

                return ({'message' : 'success'})
            
            except Exception as e:
                return [{"message":"error ", 'data' : e}]
            
        
        def get_data(self):
            try:
                cursor = db.connection.cursor()
                cursor.execute("""SELECT * FROM tbl_kepadatan_keong""")
                data = cursor.fetchall()
                cursor.close()

                return ({'message' : 'success',  'data' : data})
            
            except Exception as e:
                return ({'message' : 'error', 'data': e})

        def get_data_id(self, id):
            try:
                cursor = db.connection.cursor()
                cursor.execute("""SELECT * FROM tbl_kepadatan_keong WHERE id=%s""", (id,))
                data_id = cursor.fetchall()
                cursor.close()

                return ({'message' : 'success',  'data' : data_id})

            except Exception as e:
                return ({'message' : 'error', 'data': e})
                
        
        def save_kepadatan(self,id,data,kepadatan):
            try:
                cursor = db.connection.cursor()
                update = cursor.execute("""UPDATE tbl_kepadatan_keong SET jml_keong=%s, jml_orang=%s, jml_titik=%s, hasil=%s  WHERE id=%s""", (data['jml_keong'], data['jml_orang'], data['jml_titik'], kepadatan, id))
                db.connection.commit()
                cursor.close()
                
                return ({'message' : 'success', 'data' : update})
            
            except Exception as e:
                return ({'message' : 'error', 'data': e})

controllers/ModelController.py
from datetime import datetime
from helpers.connecttion import db

class ModelController(object):
        def __init__(self):
            pass
        def save_file(self, user, nama_gambar, nama_kelas, skor_akurasi):
            try:
                cursor = db.connection.cursor()
                cursor.execute("""INSERT INTO tbl_gambar VALUES(DEFAULT, %s, %s, %s, %s)""", (user, nama_gambar, nama_kelas, skor_akurasi))
                db.connection.commit()
                cursor.close()
                
                return ({'message': 'success'})
            
            except Exception as e:
                return [{"message":"error ", 'data' : e}]

routes/HasilRoutes.py
import os
from helpers import authRequired
from controllers import HasilController
from flask import Blueprint, render_template, session, redirect, url_for, flash

bp = Blueprint('HasilRoutes', __name__)

controller = HasilController()

@bp.route('/hasil', methods=['GET'])
@authRequired.login_required
def show_data():
        user = session.get('username')

        get_data = controller.get_file_user(user)

        if get_data['message'] == 'success':
                return render_template('menu/hasil.html', data = get_data['data'], folder=user)
        flash('Terjadi kesalahan di server')
        return redirect(url_for('BerandaRoutes.show_penjelasan'))
@bp.route('/hapus/<path:filename>', methods=['POST'])
@authRequired.login_required
def delete_file(filename):
        user = session.get('username')
        path_file = os.path.join('uploads', user, filename)
        if os.path.exists(path_file):
                delete_data = controller.delete_file_user(user, filename)
                if(delete_data['message'] == 'success'):
                        # DELETE DATA IN FOLDER USER
                        os.remove(path_file)
                        flash('Data berhasil di hapus')
                else:
                        flash('Terjadi kesalahan di server')
        else:
                flash('Data tidak ditemukan')
        return redirect(url_for('HasilRoutes.show_data'))

routes/KepadatanRoutes.py
from helpers import authRequired
from controllers import KepadatanController
from flask import Blueprint, render_template, request, redirect, url_for, flash

bp = Blueprint('KepadatanRoutes', __name__, static_folder='../', template_folder='../templates/menu')

controller = KepadatanController()

@bp.route('/kepadatan', methods=['GET', 'POST'])
@authRequired.admin_required
def show_kepadatan():
        # GET DATA FROM CONTROLER
        data_kepadatan = controller.get_data()

        # CHECK IF DATA RECEIVED
        if data_kepadatan['message'] == 'success':
                banyak_data = len(data_kepadatan['data'])
                return render_template('kepadatan.html', data=data_kepadatan['data'], banyak_data=banyak_data)
        
        # SOMETHING WRONG HAPPEN
        flash("Terjadi kesahalan di server")
        return redirect(url_for('BerandaRoutes.show_penjelasan'))

@bp.route('/save-desa', methods=['POST'])
@authRequired.admin_required
def save_desa():
        # GET DATA FROM REQUESTS
        data = request.form

        # CREATE DATA IN CONTROLLER
        create_data_desa = controller.create_data_desa(data['nama_desa'], data['jml_orang'])
        
        # IF DATA SAVED
        if create_data_desa['message'] == 'success':
                flash("Data Berhasil di simpan")
                return redirect(url_for('KepadatanRoutes.show_kepadatan'))
        
        # SOMETHING WRONG HAPPEN
        flash("Terjadi kesahalan di server")
        return redirect(url_for('KepadatanRoutes.show_kepadatan'))

@bp.route('/kepadatan/<int:id>', methods=['GET'])
@authRequired.admin_required
def show_kepadatan_by_id(id):
        # GET DATA BASED ON ID
        get_data = controller.get_data_id(id)

        if get_data['message'] == 'success':
                return render_template('kepadatan_id.html', data_id = get_data['data'])
        
        # SOMETHING WRONG HAPPEN
        flash("Terjadi kesahalan di server")
        return redirect(url_for('KepadatanRoutes.show_kepadatan')) 

@bp.route('/save-kepadatan/<int:id>', methods=['POST'])
@authRequired.admin_required
def save_kepadatan(id):
        # GET DATA FROM REQUESTS
        data = request.form

        # FORMULA KEPADATAN --> JUMLAH_KEONG / (JUMLAH_ORANG * JUMLAH_TITIK)
        kepadatan = 0
        if(int(data['jml_orang']) != 0 or int(data['jml_titik']) != 0): # IF DIVIDER != 0
                kepadatan = float(data['jml_keong']) / (float(data['jml_orang']) * float(data['jml_titik']))
                kepadatan = float("{:.2f}".format(kepadatan))


        # SAVE DATA BASED ON ID
        save_data = controller.save_kepadatan(id,data, kepadatan)

        if save_data['message'] == 'success':
                data_id = show_kepadatan_by_id(id)
                return data_id
        
        # SOMETHING WRONG HAPPEN
        flash("Terjadi kesahalan di server")
        return redirect(url_for('KepadatanRoutes.show_kepadatan'))

routes/ModelRoutes.py
import os
from controllers import ModelController
from helpers import authRequired, detect, savingFile
from werkzeug.utils import secure_filename
from flask import Blueprint, render_template, request, flash, redirect, url_for, send_from_directory, session

bp = Blueprint('ModelRoutes', __name__)

controller = ModelController()

@bp.route('/uploads/<folder>/<path:filename>')
def get_file(folder, filename):
        path_dir = os.path.join('../uploads', folder )

        return send_from_directory(path_dir, filename)

@bp.route('/model', methods=['GET', 'POST'])
@authRequired.login_required
def show_model():
        # menangani method GET
        if request.method == 'GET':
                return render_template('menu/model.html')
        # menangani method POST
        elif request.method == 'POST':
                # NO FILE
                if 'file' not in request.files:
                        flash('Tidak ada file yang dikirim')
                        return render_template('menu/model.html')
                
                file = request.files['file']

                # IF FILE DON'T HAVE NAME
                if file.filename == '':
                        flash('Tidak ada foto yang dipilih')
                        return redirect(request.url)
                
                if file and savingFile.allowed_file(file.filename):
                        # filename = secure_filename(file.filename)

                        # SAVE FILE ON USER FOLDER
                        data_save = savingFile.save_file(file)

                        if(data_save['message'] == 'exist'):
                                flash('Gambar sudah diklasifikasi, cek menu Hasil Klasifikasi')
                                return render_template('menu/model.html')
                        
                        # DETECT IMAGE
                        data_detect= detect.detect_lite(folder=data_save['folder'], filename=data_save['filename'])
                        
                        # return data_detect
                        
                                # return redirect(url_for('BerandaRoutes.show_penjelasan'))
                        # SAVE TO DB
                        user = session.get('username')
                        saving_file = controller.save_file(user, data_save['filename'], data_detect['class name'], data_detect['score'])

                        if(saving_file['message'] == 'success'):
                                flash('File berhasil di klasifikasi !')
                        # mengembalikan laman model.html dengan nama kelas hasil deteksi
                        return render_template('menu/model.html', class_name=data_detect['class name'], folder=data_save['folder'], filename=data_save['filename'], score=round(data_detect['score'],2))
                
                flash('File yang dimasukkan salah')
                return redirect(request.url)

templates/menu/beranda.html
{% extends 'base/base.html' %}

{% block title %}
    Model
{% endblock %}

{% block content %}
    <!-- <h1 class="text-5xl font-semibold my-10 text-center">Jenis-Jenis Koeng Dalam Habitat Endemik Schistosomiasis</h1> -->

<div class="flex flex-col justify-center py-10 m-10">
    <div class="self-end text-slate-900 tracking-tighter flex mb-10 gap-10 justify-center items-center">
        <img class="h-100 w-2/5 rounded-xl object-cover shadow-lg hover:shadow duration-150 shadow-black/40" src="http://127.0.0.1:5000/static/src/who.jpg">
        <div class="w-2/5 ">
            <p class="text-5xl font-bold text-center text-blue-500/80 tracking-wide">World Health Organization</p>            
            <h1 class="text-3xl text-justify mb-2 rounded-lg p-2 10 ml-3 leading-relaxed text-blue-400"><span class="italic border-b-4 border-cyan-300">Schistosomiasis</span> masuk dalam laporan <span class="italic border-b-4 border-cyan-300">WHO</span> sebagai <span class="italic border-b-4 border-cyan-300">Neglected Tropical Disease</span> atau Penyakit tropis yang terabaikan. Tahun 2016 <span class="italic">schistosomiasis</span> menyebabkan 24.000 kematian</h1>
        </div>        
    </div>
    <div class="mb-5 text-slate-900 group text-justify tracking-tight flex gap-10 justify-center items-center">
        <div class="w-2/5">
            <p class="text-5xl font-bold text-blue-500/80"><span class="hover:text-fuchsia-300 duration-200">Kementerian</span> <span class="hover:text-fuchsia-300 duration-200">Kesehatan</span> <span class="hover:text-fuchsia-300 duration-200">RI</span></p>
            <h1 class="text-3xl mb-2 rounded-lg duration-500 leading-relaxed p-2 text-blue-400">
                <span class="italic border-b-4 border-cyan-300 hover:text-fuchsia-300 duration-200">Schistosomiasis</span>
                <span class="italic border-b-4 border-cyan-300 hover:text-fuchsia-300 duration-200">di</span> Indonesia disebabkan oleh cacing <span class="italic border-b-4 border-cyan-300">Schistosoma japonicum</span> dengan hospes perantara keong <span class="italic border-b-4 border-cyan-300">Oncomelania hupensis lindoensis</span></h1>
        </div>
        <img class="h-96 w-1/3 rounded-xl object-cover shadow-lg hover:shadow duration-150 shadow-black/40 self-center" src="http://127.0.0.1:5000/static/src/kemenkes.png">
    </div>
    
    <div class="flex min-h-full flex-col py-5 bg-blue-100">
        <h1 class="text-center text-5xl font-semibold text-slate-500 mb-5">Keong-Keong Dalam Wilayah Endemik Schistosomiasis</h1>
        <div class="flex flex-wrap gap-10 justify-center">
            <div class="group h-96 w-96 [perspective:1000px]">
                <div class="relative h-full w-full rounded-xl shadow-xl transition-all duration-500 [transform-style:preserve-3d] group-hover:[transform:rotateY(180deg)]">
                    <div class="absolute inset-0">
                        <img class="h-full w-full rounded-xl object-cover shadow-xl shadow-black/40" src="http://127.0.0.1:5000/static/Keong/O.H.lindoensis.jpg">
                    </div>
                    <div class="absolute inset-0 h-full w-full rounded-xl bg-black/40 px-12 text-center text-slate-200 [transform:rotateY(180deg)] [backface-visibility:hidden]">
                        <div class="flex min-h-full flex-col items-center justify-center">
                            <h1 class="text3xl font-bold">Oncomelania hupensis lindoensis</h1>
                            <p class="text-lg">Perantara schistosomiasis</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="group h-96 w-96 [perspective:1000px]">
                <div class="relative h-full w-full rounded-xl shadow-xl transition-all duration-500 [transform-style:preserve-3d] group-hover:[transform:rotateY(180deg)]">
                    <div class="absolute inset-0">
                        <img class="h-full w-full rounded-xl object-cover shadow-xl shadow-black/40" src="http://127.0.0.1:5000/static/Keong/sulawesidrobia.jpg">
                    </div>
                    <div class="absolute inset-0 h-full w-full rounded-xl bg-black/40 px-12 text-center text-slate-200 [transform:rotateY(180deg)] [backface-visibility:hidden]">
                        <div class="flex min-h-full flex-col items-center justify-center">
                            <h1 class="text3xl font-bold">Sulawesidrobia</h1>
                            <!-- <p class="text-lg">Berada di wilayah endemik schistosomiasis</p> -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="group h-96 w-96 [perspective:1000px]">
                <div class="relative h-full w-full rounded-xl shadow-xl transition-all duration-500 [transform-style:preserve-3d] group-hover:[transform:rotateY(180deg)]">
                    <div class="absolute inset-0">
                        <img class="h-full w-full rounded-xl object-cover shadow-xl shadow-black/40" src="http://127.0.0.1:5000/static/Keong/brothia.jpg">
                    </div>
                    <div class="absolute inset-0 h-full w-full rounded-xl bg-black/40 px-12 text-center text-slate-200 [transform:rotateY(180deg)] [backface-visibility:hidden]">
                        <div class="flex min-h-full flex-col items-center justify-center">
                            <h1 class="text3xl font-bold">Brothia sp</h1>
                            <!-- <p class="text-lg">Berada di wilayah endemik schistosomiasis</p> -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="group h-96 w-96 [perspective:1000px]">
                <div class="relative h-full w-full rounded-xl shadow-xl transition-all duration-500 [transform-style:preserve-3d] group-hover:[transform:rotateY(180deg)]">
                    <div class="absolute inset-0">
                        <img class="h-full w-full rounded-xl object-cover shadow-xl shadow-black/40" src="http://127.0.0.1:5000/static/Keong/thiara.jpg">
                    </div>
                    <div class="absolute inset-0 h-full w-full rounded-xl bg-black/40 px-12 text-center text-slate-200 [transform:rotateY(180deg)] [backface-visibility:hidden]">
                        <div class="flex min-h-full flex-col items-center justify-center">
                            <h1 class="text3xl font-bold">Thiara sp</h1>
                            <!-- <p class="text-lg">Berada di wilayah endemik schistosomiasis</p> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
        perjalanan
        <p>brug tesccg </p>

    </div>
    
    

    
</div>

<script>
        // set the default active slide to the first one
        let slideIndex = 1;
        showSlide(slideIndex);

        // change slide with the prev/next button
        function moveSlide(moveStep) {
            showSlide(slideIndex += moveStep);
        }

        // change slide with the dots
        function currentSlide(n) {
            showSlide(slideIndex = n);
        }

        function showSlide(n) {
            let i;
            const slides = document.getElementsByClassName("slide");
            const dots = document.getElementsByClassName('dot');
            
            if (n > slides.length) { slideIndex = 1 }
            if (n < 1) { slideIndex = slides.length }

            // hide all slides
            for (i = 0; i < slides.length; i++) {
                slides[i].classList.add('hidden');
            }

            // remove active status from all dots
            for (i = 0; i < dots.length; i++) {
                dots[i].classList.remove('bg-yellow-500');
                dots[i].classList.add('bg-green-600');
            }

            // show the active slide
            slides[slideIndex - 1].classList.remove('hidden');

            // highlight the active dot
            dots[slideIndex - 1].classList.remove('bg-green-600');
            dots[slideIndex - 1].classList.add('bg-yellow-500');
        }
    </script>


{% endblock %}

templates/menu/hasil.html
{% extends 'base/base.html' %}

{% block title %}
    Hasil Prediksi
{% endblock %}

{% block content %}

<div class="flex gap-3 w-full  mt-5 p-4">
    <!-- <div class="max-w-md mx-auto mt-8"> -->
    {% for item in data %}
        <div class="bg-white shadow-md rounded-lg h-full ">
            <!-- Image -->
            <img src="{{ url_for('ModelRoutes.get_file', folder=folder, filename=item[2]) }}" alt="Example Image" class="w-full h-64 object-cover">
       
            <div class="p-3">
                <h2 class="text-xl font-semibold mb-2">{{item[3]}}</h2>
                <p class="text-gray-700">{{item[4]}} %</p>
            </div>
            
            <form action="{{ url_for('HasilRoutes.delete_file', filename=item[2]) }}" method="post" class="flex w-full items-end justify-end">
                <button type="submit" class="p-3 bg-red-400 text-white rounded-lg m-2">Hapus</button>
            </form>

        </div>
    {% endfor %}
    <!-- </div> -->
</div>

{% endblock %}

templates/menu/kepadatan.html
{% extends 'base/base.html' %}

{% block title %}
    Kepadatan
{% endblock %}

{% block content %}
    <h1 class="text-4xl font-semibold my-10 text-center">Kepadatan Keong</h1>

    <div class="flex flex-col w-full ">
        <div class="w-full flex flex-col justify-center items-center mb-5">
        
            <div id="open-btn">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-20 h-w-20 text-blue-500" id="open-btn">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
            </div>

            
        </div>

        <div class="mx-10">
            <div class="flex items-center flex-wrap gap-3">
                {%for i in range(0, banyak_data)%}
                <a href="{{url_for('KepadatanRoutes.show_kepadatan_by_id', id=data[i][0])}}">
        
                    <div class="border p-3 rounded-lg  text-slate-600 shadow-lg">
                        <p class="text-3xl font-semibold text-slate-700 mb-2">{{data[i][1]}} <span class="text-lg text-slate-500">{{data[i][6]}}</span></p>
                        
                        <div class="flex gap-2">
                            <div class="border-r-2 border-blue-300 pr-2">
                                <p>
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-10 h-10 inline text-blue-400">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
                                    </svg>
                                    :
                                    <span class="text-2xl">{{data[i][3]}}</span>
                                </p>
                                <p>
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-10 h-10 inline text-slate-400">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 10.5a3 3 0 11-6 0 3 3 0 016 0z" />
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1115 0z" />
                                    </svg>
                                    :
                                    <span class="text-2xl">{{data[i][4]}}</span>
                                </p>
                                <p>
                                    <img src="{{ url_for('static', filename='icon/snail.png') }}" alt="" class="w-10 h-10 inline">
                                    :
                                    <span class="text-2xl">{{data[i][2]}}</span>
                                </p>
                            </div>
                            <div>
                                <p class="text-2xl text-slate-700">Kepadatan</p>
                                <p class="text-3xl text-center">{{data[i][5]}}</p>
                            </div>
                            
                        </div>
                    </div>
                    </a>
                {%endfor%}
            </div>
        </div>
    </div>

    <div class="fixed top-0 w-full h-full hidden "  id="modal">
        <div class=" flex justify-center  w-1/2 h-full">
            <div class="relative top-20  p-5 border w-1/2 h-1/4 shadow-lg rounded-md bg-white  ">
                <div class="mt-3 text-center">
                
                    <h3 class="text-lg leading-6 font-medium text-gray-900 my-2">Buat Data Baru</h3>
                    <form action="{{ url_for('KepadatanRoutes.save_desa') }}" method="post" class="flex flex-col gap-5">
                        <div class=" flex">
                            <label for="jml_seluruh_koeng" class="text-2xl mr-4 w-80">Nama Desa : </label>
                            <input type="text" name="nama_desa" placeholder="Masukkan nama desa" class="placeholder:text-sm placeholder:italic rounded outline outline-offset-2 outline-1 outline-blue-500 text-xl ">
                        </div>
                        <div class=" flex">
                            <label for="jml_seluruh_koeng" class="text-2xl mr-4 w-80">Jumlah Orang : </label>
                            <input type="text" name="jml_orang" placeholder="Masukkan jumlah orang" class="placeholder:text-sm placeholder:italic rounded outline outline-offset-2 outline-1 outline-blue-500 text-xl ">
                        </div>
        
                        <div class="flex flex-col items-center justify-between">
                            <button type="submit" class="w-40 bg-blue-400 text-white text-2xl rounded ">Buat</button>
                        </div>
                    </form>
                    <div class="items-center px-4 py-3 absolute right-0 top-0">
                        <button id="ok-btn" class="px-4 py-2 bg-red-500 text-white
                                        text-base font-medium rounded-md w-full
                                        shadow-sm hover:bg-red-600 focus:outline-none focus:ring-2 focus:ring-purple-300">
                            X
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        let modal = document.getElementById('modal');
        let btn = document.getElementById('open-btn');
        let button = document.getElementById('ok-btn');

        btn.addEventListener('click', function openModal(){
            console.log('msdk')
            modal.classList.add('block')
        })
        btn.onclick = function () {
                modal.style.display = 'block';
            };

            button.onclick = function () {
                modal.style.display = 'none';
            };

        window.onclick = function (event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    </script>
{% endblock %}

templates/menu/model.html
{% extends 'base/base.html' %}

{% block title %}
    Model
{% endblock %}

{% block content %}
    <h1 class="text-4xl font-semibold my-10 text-center">Identifikasi Keong di wilayah endemik <i>Schistosomiasis</i></h1>

<div class="flex flex-col justify-center items-center w-full">
    <form action="{{ url_for('ModelRoutes.show_model') }}" method="post" enctype="multipart/form-data" class="w-3/4 flex flex-col ">
        <div class="w-full mr-5 ">
            <input name="file" class=" h-12  text-center w-full text-xl text-blue-900 border border-blue-400 rounded-lg cursor-pointer focus:outline-none file:rounded-lg file:h-full file:text-lg file:font-semibold file:bg-blue-100 hover:bg-blue-50 file:border-0" type="file">
            <p class="mt-1 text-sm text-gray-800" id="file_input_help">PNG, JPG or JPEG.</p>
        </div>
        <button type="submit" class="bg-blue-300 text-xl px-5 w-1/4 mt-5 self-center hover:bg-blue-400 h-10 font-semibold rounded text-white">Deteksi</button>
    </form> 
</div>

    <!-- cek apakah variabel class_name dan file_url exist -->
    {% if class_name %}
    <div class="flex justify-center my-10  ">
        <div class="flex w-1/2  justify-center items-center border">
            <img src="{{ url_for('ModelRoutes.get_file', folder=folder, filename=filename)}}" alt="" class="w-1/2 h-96">
            
            <div class="mr-5 w-1/2 self-center  ml-4">
                <h1 class="text-xl font-semibold ">Hasil : {{class_name}}</h1>
                <div class=" bg-gray-200 rounded-full ">
                    <div class="bg-green-500  font-medium text-slate-100 text-center p-1 leading-none rounded-full" style="width: {{score}}%"> Akurasi : {{score}}%</div>
                </div>
            </div>

        </div>    
    </div>
    
    {% endif %}
    

{% endblock %}